###########################################################
#    ______ _                           _        _        #
#   |  ____| |                         | |      | |       #
#   | |__  | | ___ _ __ ___   ___ _ __ | |_ __ _| |___    #
#   |  __| | |/ _ \ '_ ` _ \ / _ \ '_ \| __/ _` | / __|   #
#   | |____| |  __/ | | | | |  __/ | | | || (_| | \__ \   #
#   |______|_|\___|_| |_| |_|\___|_| |_|\__\__,_|_|___/   #
#                                                         #
###########################################################

name: {project.artifactId}
author: nicuch
main: ro.nicuch.elementals.Elementals
version: {project.version}
description: Pluginul de baza pentru serverul PikaCraft.
depend: [GroupManager, TagRegisterLib, WorldEdit, Vault, Votifier, mcMMO, ActionAnnouncer, FeatherBoard, Citizens, NoCheatPlus, AuthMe]
commands:
  show:
    description: Arata jucatorilor itemul din mana!
  randomtp:
    aliases: [rdtp, rtp]
    description: Teleportare random.
  adminchat:
    aliases: [ac]
    description: Chat pentru staff.
  chat:
    description: Comanda pentru chat.
  ps:
    description: Comanda pentru protectie.
  sound:
    description: Comanda pentru sunete.
  giveall:
    description: Comanda pentru giveall.
  points:
    description: Comanda pentru PikaPoints.
  test:
    description: Comanda folosita pentru test.
  admin:
    description: Comanda folosita de admin.
  ce:
    description: Comanda pentru custom enchants.
  achivements:
    description: Comanda pentru achivementuri.
  sort:
    description: Comanda pentru sortare.
  curse:
    description: Comanda pentru curse.